<?php

echo "<hr><h1><center>Lendo e Manipulando Pastas/Diretórios Com PHP:</center></h1><hr>";

// SCANEIA O DIRETÓRIO:
$images = scandir("images");

// VARIÁVEL CRIADA PARA JUNTAR TODAS AS INFORMAÇÕES DA VARIAVEL $INFO PARA CONVERTÊ-LA EM JSON: 
$data = array();

echo "<center>";

// var_dump($images);

// FOREACH PARA PERCORRER CADA ITEM DENTRO DO DIRETÓRIO:
foreach ($images as $img) 

{	// IN_ARRAY (QUAL É O ALVO, ARRAY())
	// O ! NO INICIO REPRESENTA A NEGAÇÃO, POIS PERCORRENDO NO FLUXO ORIGINAL SEM A NEGAÇÃO, DARIA TRUE, E O OBJETIVO É PULAR O ".", ".."
	if (!in_array($img, array(".", "..")))

	{	
		// CRIAÇÃO DE UMA VARIAVEL QUE INDICAR O CAMINHO DO ARQUIVO, QUE É IGUAL A PASTA QUE ESTÁ SENDO ACESSADA + O NOME DO ARQUIVO.	
		$filename = "images" . DIRECTORY_SEPARATOR . $img;

		// CRIAÇÃO DE UMA NOVA VARIÁVEL $INFO PARA OBTER INFORMAÇÕLES SOBRE OS ARQUIVOS.
		$info = pathinfo($filename);

		// NOVA INFORMAÇÃO ADICIONADA A VARIÁVEL $INFO, O TAMANHO EM BYTES DOS AQUIVOS.
		$info["size"] = filesize($filename);

		// NOVA INFORMAÇÃO ADICIONADA A VARIÁVEL $INFO, A DATA DE MODIFICAÇÃO DOS AQUIVOS.
		$info["modified"] = date("d/m/Y H:i:s", filemtime($filename));

		// NOVA INFORMAÇÃO ADICIONADA A VARIÁVEL $INFO, A URL DE ACESSO AOS AQUIVOS.
		// A FUNÇÃO STR_REPLACE, SERVE PARA SUBSTITUIR UMA STRING, NESSE CASO FOI USADA POR CONTA DO DIRECTORY_SEPARATOR QUE DEIXOU A BARRA AO 
		// CONTRÁRIO PARA IMPLANTAÇÃO EM SISTEMAS LINUX.
		// NO PHP, UMA BARRA \, INDICA SCAPE, POR ISSO QUANDO ESCREVEMOS UMA BARRA, TEMOS QUE COLOCAR \\.
		$info["url"] = "http://localhost/Curso%20PHP%20Udemy/014%20-%20Manipulando%20Arquivos/01%20-%20DIR" . str_replace("\\", "/", $filename);

		// var_dump($info);
		
		// AO EXECUTAR O VAR_DUMP($INFO) RETORNARÁ UM ARRAY COM 4 ELEMENTOS, A PASTA, 
		// E OS 3 ARQUIVOS DE IMAGENS DENTRO DA PASTA, COM AS SEGUINTES INFORMAÇÕES:
		
		// DIRNAME = DIRETÓRIO ONDE SE ENCONTRA O ARQUIVO.
		// BASENAME = NOME DO ARQUIVO + A EXTENSÃO.
		// EXTESION = EXTENSÃO DO ARQUIVO.
		// FILENAME = NOME DO ARQUIVO SEM A EXTENSÃO. 

		// ARRAY_PUSH PARA COLOCAR A VARIÁVEL $INFO DENTRO DO ARRAY $DATA:
		// O PRIMEIRO PARÂMETRO É O ARRAY E O SEGUNDO A VARIÁVEL. 
		array_push($data, $info);
	}

}
	// CONVERTER O ARRAY $DATA QUE RECEBEU $INFO EM JSON
	echo json_encode($data);

echo "</center>";

?>