<?php

echo "<hr><h1><center>Criando Arquivos Com fopen():</center></h1><hr>";

// FUNÇÃO FOPEN, PARA ABRIR UM ARQUIVO; ESSA FUNÇÃO ESPERA 2 PARÂMETROS, OS DOIS DO TIPO STRING: O 1º É PARA INDICAR O CAMINHO DO ARQUIVO, O 2º DETERMINA O TIPO DE CONTROLE SOBRE O ARQUIVO, POR EXEMPLO: 
/* SOMENTE LER O CONTEÚDO; 
 LER, ARESCENTAR ALGO NO ARQUIVO, ALTERAR/MODIFICAR ALGUMA INFORMAÇÃO;
 SÓ ALTERAR; 
 OBS: NA DOCUMENTAÇÃO PHP, EM PHP.NET, TEM UMA TABELA DE VARIAÇÕES QUE PODEM SER USADAS COMO PARÂMETROS PARA O FOPEN.
OBS²: NO SEGUNDO PARÂMETRO, TUDO O QUE VIER COMO +, SIGNIFICA QUE O ARQUIVO NÃO EXISTE, E EU IREI CRIÁ-LO.
*/

// W+ SIGNIFICA WRITE, E O +, QUE O ARQUIVO NÃO EXISTE E É PARA CRIÁ-LO.
// $file = fopen("log.txt", "w+");
// NESSE MOMENTO A VARIÁVEL $FILE É UMA VARIÁVEL INSOURCE, POIS FAZ REFERÊNCIA À UM ARQUIVO EXTERNO:

$file = fopen("log.txt", "a+");

// FUNÇÃO PARA ESCREVERMOS DENTRO DO ARQUIVO:
// ESSA FUNÇÃO TBM RECEBE DOIS PARÂMETROS:
// O 1º, UM RESOURCE: UM CONTROLADOR OU UM ARQUIVO, NESSE CASO A VARIÁVEL $FILE.
// O 2º, O QUE SE DESEJA ESCREVER NO ARQUIVO.
fwrite($file, date("Y-m-d H:i:s") . "\r\n");

// APÓS O TÉRMINO DA MANIPULAÇÃO DO ARQUIVO, É PRECISO FECHÁ-LO, PARA ISTO A FUNÇÃO FCLOSE:
fclose($file);

echo "<hr><h3><center>" . "O arquivo foi criado com sucesso!" . "</center></h3><hr>";

?>